### ISSUE TITLE
Allow Users to get YLT Reports by mail

### ISSUE THREAD

**Issue by ousamabenyounes** [YellowLabTools/YellowLabTools#163]
It would be interesting to allow users to fill their email once the test is launched.
So if there is lot of tests running, or if we get a technical issue on the server, user will be able to get noticed later of their test report...

**Comment by gmetais** [comment]
I don't realize, do you often wait a long time before getting the result?

Of course I'd prefer to reduce the waiting time and the number of technical issues, but I see your idea as a short term solution.

I hate websites that collects emails, so the GUI will need to clearly specify that emails won't be collected and used. Also, for the moment, if the server experiences a technical issue, the waiting queue is emptied as there's not database.

I just got an alternative idea: pop a [web notification](http://caniuse.com/#feat=notifications) when the test is complete and change the favicon's color. Much simpler to implement. What do you think?

**Comment by ousamabenyounes** [comment]
Nice idea...

But I was strongly thinking on this solution because when their is too many users using YLT at the same time, lot of them will get a bad experience of YLT.
We can think about adding VMs, but I think we must also think about this feature to allow users not loosing their reports...

**Comment by ousamabenyounes** [comment]
I'll may like to see YLT history of a tested url.
For exemple, I tested a website today with a friend.
I obtained 0/100. But one month ago I remember this website was having 30/100.
So it is interesting for me to get a graphical presentation of this website url history?
I am waiting to get my result, but during this waiting time, i Could see this graphic? 
This also shows me that somebody else allready tested this url X times.

What do you think about it?

**Comment by gmetais** [comment]
This is a nice idea, it's a good way to make the loading time appear shorter and to add some supsense!

It depends on #107.

**Comment by ousamabenyounes** [comment]
I close this issue because the queue is disabled, and you can now have feedback more quickly thanks to @ohoareau migration :)
