### ISSUE TITLE
Error 255: Phantomas error

### ISSUE THREAD

**Issue by gmetais** [YellowLabTools/YellowLabTools#168]
The Error 255 happens on some website. The reason is not known for the moment. It could be related to PhantomJS crashing when trying to record too many DOM accesses.

**If you encounter this bug** and would like to help finding the root cause, **please add a comment** with the following template:

**Webpage URL:** `http://www.rueducommerce.fr/`
**Tested device:** `desktop`
**Makes a redirection:** `yes, from / to /home/index.htm`
**Other information that could help debugging:** `this website loads a huge amount of JS (872 kilobytes)`

**Comment by gmetais** [comment]
I'm reposting #202 here:

**Webpage URL:** https://www.1und1.de/
**Tested device:** desktop
**Makes a redirection:** No
**Other information that could help debugging:** this website loads a huge amount of JS (522 kilobytes)

Then i run yellowlabs as local service I dont get the error, but I get all pounts as grenn and ok. But I know, by this domain nothing is ok.

**Comment by brain11f** [comment]
Error 255: Phantomas error

Webpage URL: http://overstock.com
Tested device: desktop/chrome
Makes a redirection: no
Other information that could help debugging: React?

**Comment by rockeynebhwani** [comment]
Error 255: Phantomas error

Webpage URL: http://direct.asda.com/george/womens/lingerie/lingerie-sets/entice-lace-trim-balcony-bra-brazilian-knickers/SET2313,default,pd.html
Tested device: desktop
Makes a redirection: no
Other information that could help debugging: Result URL - http://yellowlab.tools/queue/epaux2wvs9

**Comment by stefounet** [comment]
Any news on this issue? I still get the error on www.rueducommerce.fr/home/index.html

**Comment by fpaterno** [comment]
Test failed
Error 255: Phantomas error

**Webpage URL:** https://www.plusbellelavie.fr/
**Tested device:** desktop
**Makes a redirection:** No

**Comment by anirudhwarrier** [comment]
Test failed
Error 255: Phantomas error

**Webpage URL**:  https://www.pattersondental.com/
**Tested device**: desktop
**Makes a redirection**: No

**Comment by gmetais** [comment]
Should be fixed by #322.
