### ISSUE TITLE
Error 1001: JavaScript profiling failed

### ISSUE THREAD

**Issue by gmetais** [YellowLabTools/YellowLabTools#170]
The Error 1001 happens on some websites, but the reason is not understood yet. It _could_ be a problem with the "Prototype" or the "Mootools" JS frameworks.

**If you encounter this bug** and would like to help finding the reason, **please add a comment** with the following template:

**Webpage URL:** `http://www.consoanimo.com/`
**Tested device:** `desktop`
**Prototype version:** `1.6.0.3`
**Mootools version:**  `not used`
**Other information that could help debugging:** ` `

Edit @gmetais: fixed by #197.

**Comment by gmetais** [comment]
Importing this occurrence from #159.

**Webpage URL:** `https://www.airbnb.com/rooms/5947318?checkin=09%2F09%2F2016&checkout=09%2F16%2F2016&guests=2&s=X_4uf2gu`
**Tested device:** `desktop`
**Prototype version:** `probably not used`
**Mootools version:**  `probably not used`
**Other information that could help debugging:** `A lot of JS, 685KB (gzipped). Crashed my local instance when testing, the test ends but the failing promise doesn't seem to be handled properly.`

**Comment by jpvincent** [comment]
Same error number here :

Webpage URL  : http://m.vogue.fr/hbt/dossier/fashion-week-homme/1167
Tested device : mobile
Prototype : not used
Mootols : not used
Other : lot of ads …

**Comment by gmetais** [comment]
I just fixed a bug that was causing a 1001 error. It will be released in v1.12.0 some time later.

If you still encounter this bug, please make sure you're using v1.12 or higher (version is shown at bottom of the page). If you are and still have the bug, please add a entry :)

**Comment by ne0-cz** [comment]
Webpage URL: `https://corona-academy.com/`
Tested device: `desktop`
Prototype version: `not used`
Mootools version: `not used`
Other information that could help debugging:

Tested with v1.13.2 (public and private docker instance). The Error is caused by the chat widget from Freshdesk - without it the Error does not occur. Since it's third party JavaScript I can't really help with it - it might even use one of Prototype / Mootools.

**Comment by gmetais** [comment]
Fixed by #327.
