### ISSUE TITLE
Test failed with timeout on heavy JS website

### ISSUE THREAD

**Issue by psa-jforestier** [YellowLabTools/YellowLabTools#271]
Site : http://cfgv3.awsmpsa.com/index.html
On the https://yellowlab.tools : it finish with a 404 after 2 minutes.
When I run the Docker container you provided, it ended with the following error on the console : 
`Killing phantomas because the test on http://cfgv3.awsmpsa.com/index.html was launched 150 seconds ago`
(and the container is stoped)

By executing step-by-step test, I sawFantomas.js is in an infinite loop after loading some ressources.

Note this website is using a lot of JS because of the REACT framework.

**Comment by gmetais** [comment]
Hi!

Sorry for the late answer, I somehow completely missed the notification for you issue...

I get the same problem when launching Phantomas standalone and definitely looks like an infinite loop:

```phantomas http://cfgv3.awsmpsa.com/index.html --verbose```

Do you mind opening an issue on that project?

**Comment by gmetais** [comment]
Should be fixed by #322.
