### ISSUE TITLE
PhantomJS Chrome Headless Future

### ISSUE THREAD

**Issue by stephengroat** [YellowLabTools/YellowLabTools#272]
Since [PhantomJS seems to be stopping dev](https://news.ycombinator.com/item?id=14105489) and [Chrome Headless started shipping with v59](https://developers.google.com/web/updates/2017/04/headless-chrome), I'm wondering what the future direction is with this project. I use it and love it, but I've only dealt with headless chrome in ruby (never in js), so I don't know how much help I could be!
Thanks again for all the great work!

**Comment by gmetais** [comment]
Hi!

YLT is based on Phantomas, which is based on PhantomJS. However, the Phantomas project is considering switching to Chrome. Take a look here: https://github.com/macbre/phantomas/issues/707

**Comment by stephengroat** [comment]
Great news, thanks for the info!

**Comment by gmetais** [comment]
Done by #322.
