### ISSUE TITLE
Error 4294967295 on Windows

### ISSUE THREAD

**Issue by hitesh0078** [YellowLabTools/YellowLabTools#273]
i got error when run in my local pc.

engine "webkit" not found!?

**Comment by gmetais** [comment]
Hi,

It looks like the PhantomJS engine could not install correctly. Could you please try to uninstall/reinstall and look for any installation errors?

Also, what OS are you on and what version of Node do you use?

**Comment by hitesh0078** [comment]
after reinstall, Error has been changed 
check below images
![screenshot_1](https://user-images.githubusercontent.com/39802295/40837703-f0b3a878-65b8-11e8-9877-e4b20142e044.jpg)
![screenshot_2](https://user-images.githubusercontent.com/39802295/40837704-f0e10430-65b8-11e8-8d72-b206e3343004.jpg)

**Comment by gmetais** [comment]
Hi,

This number equals 0xffffffff in hexadecimal. It looks like Windows is upset, by something, but I don't know what.

What version of Node do you use?

**Comment by hitesh0078** [comment]
Node.js foundation 8.11.2  ,

**Comment by gmetais** [comment]
Sorry, I still have no clue about this error. It looks like a PhantomJS error on Windows...

**Comment by gmetais** [comment]
Similar to #150.
