### ISSUE TITLE
Update user agents to match with recent devices

### ISSUE THREAD

**Issue by gmetais** [YellowLabTools/YellowLabTools#281]
- Remove the "tablet" device (not often used).
- Separate mobiles in "low-end mobile" and "high-end mobile".
- Turn on 3x pixels density screens to high-end mobiles.

**Comment by jpvincent** [comment]
chrome does have an option to emulate certain "famous" mobiles, you could use it ?

**Comment by gmetais** [comment]
Fixed by #327.
