### ISSUE TITLE
Reduce impact of sprites/concatenation on score

### ISSUE THREAD

**Issue by gmetais** [YellowLabTools/YellowLabTools#286]

**Comment by jpvincent** [comment]
maybe keep it in the score only for HTTP 1.1 and remove it entirely if HTTP/2 is detected ?

**Comment by gmetais** [comment]
Yes, let's do that.

**Comment by ozcoder** [comment]
At $WORK we have a sprite because we still need to support old IE browsers :(

**Comment by gmetais** [comment]
Sprites are actually good, @ozcoder 👍

**Comment by gmetais** [comment]
Fixed by #322. Small requests metric was removed completely, the total number of requests is sufficient.
