### ISSUE TITLE
Private instance tests fail TypeError: Bad argument

### ISSUE THREAD

**Issue by jdmevo123** [YellowLabTools/YellowLabTools#307]
Getting TypeError: Bad argument when trying to run tests.

Ubuntu EC2 Instance
node: v6.17.1
NPM: 3.10.10

**Comment by gmetais** [comment]
Hi @jdmevo123,
Is it when you launch a test from the command line, or is it when you start the server then launch a test from the UI?

**Comment by jdmevo123** [comment]
Hi @gmetais,

Yes it’s from the UI when trying to launch a test.

**Comment by gmetais** [comment]
Hi, I'm publishing a new major version. Do you mind retrying from the `develop` branch?
