### ISSUE TITLE
Different scores between online tool and Node package

### ISSUE THREAD

**Issue by smth** [YellowLabTools/YellowLabTools#314]
Just trying out the Node package and am seeing that the `globalScore` is different to the one I get when testing the same URL with [online tool](https://yellowlab.tools/). This doesn't seem to be a fluctuation, as the scores are consistently different (by 5 points) when retesting. Is this to be expected? Down to location perhaps?

I can't tell exactly how category scores compare, as they are not exposed on the site, as far as I can tell.

**Comment by gmetais** [comment]
Hi @smth,
It could indeed be related to location. Some websites redirect users based on IP address and the server is hosted in Paris, France. Does your website do this kind of thing?

The weights of each rule and each category score are here: https://github.com/YellowLabTools/YellowLabTools/blob/master/lib/metadata/scoreProfileGeneric.json (rules first, categories at the end of the file).

**Comment by smth** [comment]
The site I'm testing does use a (Netlify) CDN, so yeah. Why I was confused about this though is that I'm not sure why this would make a difference, given the metrics that YLT uses. It's not measuring speed, as far as I can see; and I would have though everything else would be consistent across servers.

**Comment by smth** [comment]
I think I may have found the discrepancy, though I still don't understand it. The Node version seems to be reporting fonts incorrectly in my test case. It is reporting the number of fonts used on the desktop version, despite being configured to test on mobile. `params.options.devices` states `mobile`.

**Comment by gmetais** [comment]
Could it be a typo? `params.options.device` without `s`.

**Comment by smth** [comment]
Yes, that was a typo (this of course has no bearing on the issue).

**Comment by gmetais** [comment]
Oh, I remember now, params.options.devices should be "phone" instead of mobile.
