### ISSUE TITLE
No rule scores from Node package

### ISSUE THREAD

**Issue by smth** [YellowLabTools/YellowLabTools#315]
Is it possible to get the rule scores when using the Node package?

Here is an example of what I'm getting:

```js
"pageWeight":{
  "label":"Page weight",
  "categoryScore":100,
  "rules":[
    "totalWeight",
    "imageOptimization",
    "imagesTooLarge",
    "gzipCompression",
    "fileMinification"  
  ]
}
```

I would expect each of those rules to contain a label and some data. Something like:

```js
"rules":[
  "totalWeight": {
    "label":"Total weight",
    "result":"10KB",
    "score":90
  },
  "imageOptimization": {}
]
```

**Comment by gmetais** [comment]
You should have them in another part of the JSON.

```
"rules": {
    "DOMelementsCount": {
      "value": 880,
      "policy": {
        "tool": "phantomas",
        "label": "DOM elements count",
        "message": "A high number of DOM elements means a lot of work for the browser to render the page.",
        "isOkThreshold": 1000,
        "isBadThreshold": 3000,
        "isAbnormalThreshold": 5000
      },
      "bad": false,
      "abnormal": false,
      "score": 100,
      "abnormalityScore": 0,
      "offenders": [
        "foo",
        "bar"
      ]
    },
    "DOMelementMaxDepth": { ... }
```

Check here: https://github.com/YellowLabTools/YellowLabTools/wiki/JSON-output-format

**Comment by smth** [comment]
Ah I see. It seems some of the keys do not match up, which makes this difficult to work with. If you loop through the rules in the `scoreProfiles` section, you don't always get a corresponding rule in the `rules` section.

**Comment by gmetais** [comment]
Some rules depend on other rules, could it be this? I'm thinking about some jQuery rules that are not there when jQuery is not loaded on the page.
