### ISSUE TITLE
CLI on Alpine gives install error Cannot find module 'internal/util/types'

### ISSUE THREAD

**Issue by krompaco** [YellowLabTools/YellowLabTools#317]
I have a Docker image from alpine:3.10.3 where I try to get the CLI working.

The other relevant versions should be below. I have triple checked the requirements... Any help is appreciated.

```
/usr/bin/yellowlabtools -> /usr/lib/node_modules/yellowlabtools/bin/cli.js

> thread-sleep@1.0.4 install /usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.9
node-pre-gyp info using node@10.19.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep/lib/binding/Release/node-v64-linux-x64/thread_sleep.node" (not found)
node-pre-gyp http GET https://node-pre-gyp-forbeslindesay.s3.amazonaws.com/thread_sleep/v1.0.4/Release/thread_sleep-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:692:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
node-pre-gyp ERR! System Linux 4.19.128-microsoft-standard
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/yellowlabtools/node_modules/thread-sleep
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

**Comment by marcuslindblom** [comment]
I don't have a solution to this specific problem but if you struggle with building an alpine image with yellowlabtools cli you might found my Dockerfile useful.
```
FROM node:alpine3.12

RUN apk add --update --no-cache curl jq &&\
  cd /tmp && curl -Ls https://github.com/dustinblackman/phantomized/releases/download/2.1.1/dockerized-phantomjs.tar.gz | tar xz &&\
  cp -R lib lib64 / &&\
  cp -R usr/lib/x86_64-linux-gnu /usr/lib &&\
  cp -R usr/share/fonts /usr/share &&\
  cp -R etc/fonts /etc &&\
  curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf - &&\
  cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs &&\
  rm -rf /tmp/*

RUN npm install -g yellowlabtools

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by gmetais** [comment]
Hi,

I'm currently working on the next version of YLT, based on Phantomas v2. This version will replace the old PhantomJS browser by Chrome headless. I've also updated some dependencies and jumped the required Node version from <=8 to >= 12.

It could solve some problems. Do you mind testing building your docker image from the branch ylt-v2, to see if you still experiment these problems?

I know that @ousamabenyounes is also trying to build an alpine image right now, he might be able to help you soon :)

**Comment by ousamabenyounes** [comment]
Hi, 

I am working on this subjet as gmetais explained.
I pushed the dockerfile on github here => https://github.com/ousamabenyounes/alpine-docker-yellowlabtools
and linked  it to docker hub here => https://hub.docker.com/repository/docker/ousamabenyounes/yellowlabtools/builds

build is ok
yellowlabtools runs with debug mode for the moment
we are getting some issue and with yellowlabtools debug mode enabled we will be able to understand what is happening

other problem, the size of this container wich is too big
first we are looking with gael a way to fix the curent issue (yellowlabtool is freezing - "test is running")
then if this is fixed, we ll be cleaning the dockerfile and removing all not needed dependency so the image will be tinier (we hope...)

Any help is welcome to fix those issue and merge request are welcome :)

**Comment by ousamabenyounes** [comment]
After some tests, we found that this image is working fine
You can try it running following command:

`docker run --privileged -p 8383:8383 -it   ousamabenyounes/yellowlabtools
`
This docker image is running the YellowLabTools V2 version and i will try to make this image tinier because it still uses 2go 

(I am sorry for the time spent to deliver this feature but i am still ill and I hope to be better soon)

Regards

**Comment by krompaco** [comment]
> `docker run --privileged -p 8383:8383 -it ousamabenyounes/yellowlabtools `

Works great for me, thanks!

**Comment by ousamabenyounes** [comment]
For information, the last version of our docker container is now 1,3go
We will work on making it better adding docker multi stage when possible (to remove unecessary tools from container)
