### ISSUE TITLE
Variables in URL testing

### ISSUE THREAD

**Issue by uhlhosting** [YellowLabTools/YellowLabTools#319]
Hi,

We are using pagespeed local with nginx: 

- there are several improvements with pagespeed on
- there is a option https://site.name/?PageSpeed=off to disable pagespeed temporary to do testing comparison.
- noticed that Yellow Lab does not know to work with such urls, any plans to fix this?
- the error received: 

>  Test failed
>  Error 254: page loading failed in PhantomJS

**Comment by uhlhosting** [comment]
```
Launching test ftt1jqzfnv on https://www.google.com
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
fs.js:143
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:143:11)
    at Object.rmdir (fs.js:727:14)
    at Dir.rmdir (/usr/src/ylt/node_modules/temporary/lib/dir.js:44:12)
    at /usr/src/ylt/lib/screenshotHandler.js:160:33
    at FSReqCallback.oncomplete (fs.js:146:23) {
  code: 'ERR_INVALID_CALLBACK'
}
```

This basically kills the docker image.

**Comment by uhlhosting** [comment]
IMHO this project its officially unsuported and unsafe to run on premises.
- There are several packaged completely unsuported, not to mention the broken errors from building it. 
- If someone would like to care to fork it and fix it, guess this would be best idea.

**Comment by uhlhosting** [comment]
It seems the current config, for some reassons will not work with any NodeJS higher than 9.xx.x . I tested 10 , 11, 12, 13, 14, 15. It seems the issue its with fs variables that changed their requirements in later NodeJS version.

```
Launching test ftt5lxxbe2 on https://uhl.site/
(node:1) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

Ofcourse it is buggy, especially if runned on mobile or so, yet there is big potentioal here, just too bad not much active users @ the community.

**Comment by gmetais** [comment]
Hi @uhlhosting,
The project is currently active on branch ylt-v2. There is still some work in progress, but at least it is updated and compatible with newer Node versions. Do you mind checking?

**Comment by gmetais** [comment]
Regarding parameters in URLs, they are supported. It might just be an error with PhantomJS on the page. The v2 should fix it.
