### ISSUE TITLE
Waiting behind 1 other test - OnPremise

### ISSUE THREAD

**Issue by uhlhosting** [YellowLabTools/YellowLabTools#320]
Just deployed this via docker, surely no one knows the address and port, so how come this tells me by default i'm behind another test?

> Yellow Lab  Tools
> 
> Tested url:   https://uhl.site/
> 
> Waiting behind 1 other test
> (auto-refresh activated)

**Comment by gmetais** [comment]
Well, this is very strange. Which docker file do you use? Did you test that new one?
ousamabenyounes/yellowlabtools

**Comment by uhlhosting** [comment]
> Well, this is very strange. Which docker file do you use? Did you test that new one?
> ousamabenyounes/yellowlabtools

Used all versions 1.13.3/4

**Comment by uhlhosting** [comment]
@gmetais where is the v2 beta release?
