### ISSUE TITLE
Problem to run local test on docker image

### ISSUE THREAD

**Issue by koala819** [YellowLabTools/YellowLabTools#342]
I would like to test my project with the YelloLabTools but I have this error

I used it on Windows 10 with WAMP and with the LiveServer on VisualStudio Code
I test the www.google.fr and work OK 

`Error: net::ERR_CONNECTION_REFUSED at http://localhost/index.php
    at navigate (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16)
    at async Page.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:789:16)
    at async /usr/src/ylt/node_modules/phantomas/lib/browser.js:265:7
Test failed for URL: http://localhost/index.php
Phantomas failed: net::ERR_CONNECTION_REFUSED at http://localhost/index.php`

It's a a great tool to know how to improve the code.
And say how to do it it's just magic ^^

**Comment by ousamabenyounes** [comment]
Thank you @koala819 for this issue and your feedback

I just found a way to test your local web server. 

replace 
http://localhost:8080/ 
by
http://host.docker.internal:8080/

it is well documented here and seems to work on mac and windows
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

Regards,
Ousama.

**Comment by gazdagergo** [comment]
Hello @ousamabenyounes, thanks for the reply to this issue. However I am still facing it on my mac.
- I've followed [your instructions](https://github.com/ousamabenyounes/docker-yellowlabtools#usage) on container setup and run: 
I've executed `docker run --privileged -p 8383:8383 --name yellowlab ousamabenyounes/yellowlabtools`
and my yellowlab is running on `http://localhost:8383`
  
- my site to test is running and available on both
  - http://localhost:8080
  - http://docker.for.mac.localhost:8080/
  - (not under http://host.docker.internal:8080/)

However inputing http://docker.for.mac.localhost:8080/ on local yellowlab test site I get `Phantomas failed: net::ERR_CONNECTION_REFUSED at http://docker.for.mac.localhost:8080/` error.
