### ISSUE TITLE
Incorrect Ratings - changes on refresh

### ISSUE THREAD

**Issue by oitconz** [YellowLabTools/YellowLabTools#345]
I put in a web site for testing and got an F.  The test claimed there were 99 not https requests, lots of slow pages etc. 

On rerunning the test i got an A. 

There is something not right in the tests. 

https://gourmetdirect.co.nz was the tested site.

**Comment by gmetais** [comment]
Hi @oitconz,

Actually your website uses a CDN that is not always enabled. On the first page call, resources are served from your domain with HTTP/1. Once cached, successive calls are served from Nitropack's CDN.

There is nothing I can do on Yellow Lab Tools' side.

**Comment by oitconz** [comment]
Thanks - thats interesting.

I'll get in contact with the hoster / CDN as that should not happen.

shane


------ Original Message ------
From: "Gaël Métais" ***@***.***>
To: "YellowLabTools/YellowLabTools" ***@***.***>
Cc: "oitconz" ***@***.***>; "Mention" 
***@***.***>
Sent: 19/05/2021 11:34:19 am
Subject: Re: [YellowLabTools/YellowLabTools] Incorrect Ratings - changes 
on refresh (#345)
