### ISSUE TITLE
How do we update our private instance to v2.0?

### ISSUE THREAD

**Issue by mikeott** [YellowLabTools/YellowLabTools#351]
We've been running it on Ubuntu for a while, and would like to update to v2.0. Nothing mentioned in the docs on how to do that.

Thanks in advance.

**Comment by ousamabenyounes** [comment]
Hi @mikeott 

I recommand you to use the last official docker image. 
So you will be able to run a YellowLabTools V2 instance very easily.

As seen on the documentation:

"The Docker image - ousamabenyounes/docker-yellowlabtools
Your own private instance of Yellow Lab Tools, on your computer."

=> https://github.com/ousamabenyounes/docker-yellowlabtools

Do not hesitate to reopen this issue if you get trouble on launching YLT V2.

Regards
