### ISSUE TITLE
lazy loading is not working

### ISSUE THREAD

**Issue by GabrielLeandroBS** [YellowLabTools/YellowLabTools#357]
The lazy loading metric I made doesn't recognize Lozad's class a or Native loading, I've already defined a minimum height and width, could you help me with this issue? Thanks.

Here is my image that is not being verified and not being recognized.

![image](https://user-images.githubusercontent.com/48261292/145414625-d7846d3d-da17-4fd5-aaa1-042080ab949d.png)

**Comment by jitendravyas** [comment]
Yes This needs to be improved

**Comment by gmetais** [comment]
Because it is a duplicate of https://github.com/YellowLabTools/YellowLabTools/issues/333.
