### ISSUE TITLE
Phantomas

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [YellowLabTools/YellowLabTools#358]
Is it possible to update your phantomas dependency to the version 2.3.0 ?

This is mainly to get rid of a node-sass sub-dependency from analyze-css. analyse-css have migrated to dart-sass, with make less installl problems (node-sass building is not fun)

**Comment by gmetais** [comment]
Hello @ZatsuneNoMokou,

Thanks for the suggestion (and for your previous raised bugs). I'm quite busy at the moment, but I'll try to do that in the second half of January.

**Comment by ZatsuneNoMokou** [comment]
You're welcomed

**Comment by jurbe** [comment]
Hi @gmetais,
@kevinkammleiter made some great changes to phantomas, which were release in 2.4.0. There's already a PR: https://github.com/YellowLabTools/YellowLabTools/pull/359
Would be absolutely great if you can update directly to 2.4.0

**Comment by chritophe-ledu** [comment]
Is it possible to merge that pr ?

**Comment by gmetais** [comment]
Done, sorry for the delay. The new YLT version is 2.2.0.

**Comment by ZatsuneNoMokou** [comment]
I think that in your doc (https://github.com/YellowLabTools/YellowLabTools/wiki/Command-Line-Interface), node-gyp is no longer needed, as the node-sass that needed it is no longer used (except if there another dependency that need it)

**Comment by gmetais** [comment]
Thanks for the info, this is fixed :)
