### ISSUE TITLE
make final page score less forgiving of issues.

### ISSUE THREAD

**Issue by Jieiku** [YellowLabTools/YellowLabTools#370]
The final page score is often 90+ even with a lot of issues.

Out of ALL Zola themes I tested only 4 of them scored lower than 90: https://github.com/Jieiku/zola-themes/blob/main/README.md

PS: I love that YellowLabTools goes into more detail than google lighthouse on many possible issues.

**Comment by gmetais** [comment]
Not sure everybody would agree with your idea. Especially people who have a 0/100 score 😄

**Comment by Jieiku** [comment]
I actually found a solution that gives a more granular score. I make an average from all of the category scores and use that instead of the global score.
