### ISSUE TITLE
On pages with no JS - "Total JS execution time" is non-zero

### ISSUE THREAD

**Issue by phloe** [YellowLabTools/YellowLabTools#371]
Tiny niggle - you still get an A-rating - but it's just weird that execution time is not 0.

<img width="957" alt="Screenshot 2022-11-07 at 20 37 09" src="https://user-images.githubusercontent.com/13237/200399118-a3da7500-3df3-40cd-825c-b0f0e75c844e.png">

**Comment by gmetais** [comment]
Hi @phloe, you are right, this is weird. It might because Phantomas instrumentalizes the page by injecting some JS. Not sure how to fix that, except by removing 19ms from the metric.

**Comment by phloe** [comment]
That sounds like a plausible explanation.

There could just be a footnote or something to document it?
