### ISSUE TITLE
Where does the results are stored? 

### ISSUE THREAD

**Issue by planetahuevo** [YellowLabTools/YellowLabTools#374]
I am testing a private instance. Thank you for such great tool! 

I am trying to be able to clean up results using a cron. 

I found the folder /results/ with the json and the screenshot. 
I wonder if there is any other thing I need to delete apart from the folders there, and also if deleting that directly will cause any issues to the tool.

Thanks

**Comment by gmetais** [comment]
Hi @planetahuevo, you're right, the results are stored in `results`. On some machines, some files stay stuck in `/tmp/`.

You can safely delete all these files. But let the tool a few seconds to display the results before deleting them, otherwise you'll have a 404 error on the results page :)
